development:
  adapter: postgresql
  encoding: unicode
  database: my_app_dev
  pool: 5
  username: maksim
  password: 1011

test:
  adapter: postgresql
  encoding: unicode
  database: my_app_test
  pool: 5
  username: maksim
  password: 1011